# Generated by Django 6.0.7 on 2026-07-26 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#1d4ed8', max_length=7, verbose_name='Cor primária')),
                ('cor_secundaria', models.CharField(default='#f59e0b', max_length=7, verbose_name='Cor secundária')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de expiração')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
